"""
This type stub file was generated by pyright.
"""

from typing import List, Optional  # noqa: UP035

from drain3.drain import LogCluster  # type: ignore
from drain3.persistence_handler import PersistenceHandler  # type: ignore
from drain3.template_miner_config import TemplateMinerConfig  # type: ignore

logger = ...
config_filename = ...
ExtractedParameter = ...

class TemplateMiner:
    def __init__(self, persistence_handler: PersistenceHandler = ..., config: TemplateMinerConfig = ...) -> None:
        """
        Wrapper for Drain with persistence and masking support

        :param persistence_handler: The type of persistence to use. When None, no persistence is applied.
        :param config: Configuration object. When none, configuration is loaded from default .ini file (if exist)
        """

    def load_state(self) -> None: ...
    def save_state(self, snapshot_reason) -> None: ...
    def get_snapshot_reason(self, change_type, cluster_id) -> Optional[str]:  # noqa: UP045
        ...
    def add_log_message(self, log_message: str) -> dict: ...
    def match(self, log_message: str, full_search_strategy=...) -> LogCluster:
        """
        Mask log message and match against an already existing cluster.
        Match shall be perfect (sim_th=1.0).
        New cluster will not be created as a result of this call, nor any cluster modifications.

        :param log_message: log message to match
        :param full_search_strategy: when to perform full cluster search.
            (1) "never" is the fastest, will always perform a tree search [O(log(n)] but might produce
            false negatives (wrong mismatches) on some edge cases;
            (2) "fallback" will perform a linear search [O(n)] among all clusters with the same token count, but only in
            case tree search found no match.
            It should not have false negatives, however tree-search may find a non-optimal match with
            more wildcard parameters than necessary;
            (3) "always" is the slowest. It will select the best match among all known clusters, by always evaluating
            all clusters with the same token count, and selecting the cluster with perfect all token match and least
            count of wildcard matches.
        :return: Matched cluster or None if no match found.
        """

    def get_parameter_list(self, log_template: str, log_message: str) -> List[str]:  # noqa: UP006
        """
        Extract parameters from a log message according to a provided template that was generated
        by calling `add_log_message()`.

        This function is deprecated. Please use extract_parameters instead.

        :param log_template: log template corresponding to the log message
        :param log_message: log message to extract parameters from
        :return: An ordered list of parameter values present in the log message.
        """

    def extract_parameters(
        self, log_template: str, log_message: str, exact_matching: bool = ...
    ) -> Optional[List[ExtractedParameter]]:  # type: ignore # noqa: UP006, UP045
        """
        Extract parameters from a log message according to a provided template that was generated
        by calling `add_log_message()`.

        For most accurate results, it is recommended that
        - Each `MaskingInstruction` has a unique `mask_with` value,
        - No `MaskingInstruction` has a `mask_with` value of `*`,
        - The regex-patterns of `MaskingInstruction` do not use unnamed back-references;
          instead use back-references to named groups e.g. `(?P=some-name)`.

        :param log_template: log template corresponding to the log message
        :param log_message: log message to extract parameters from
        :param exact_matching: whether to apply the correct masking-patterns to match parameters, or try to approximate;
            disabling exact_matching may be faster but may lead to situations in which parameters
            are wrongly identified.
        :return: A ordered list of ExtractedParameter for the log message
            or None if log_message does not correspond to log_template.
        """
